### ISSUE TITLE
Can't see the summary line

### ISSUE THREAD

**Issue by Lowfeye** [pasqualedante/Noctis-visual-studio#1]
![Snipaste_2023-04-26_18-49-05](https://user-images.githubusercontent.com/116878849/234553345-3a9a6de0-e87f-4858-825f-7dbfdd0ede22.png)

**Comment by JobAbout** [comment]
Tools -> Options -> Fonts and Colors -> Editor Tooltip -> Item foregrounp: White

**Comment by Lowfeye** [comment]
Tools -> Options -> Fonts and Colors -> Editor Tooltip -> Item foregrounp: White

**Comment by pasqualedante** [comment]
@JobAbout  thanks for your report: even if a user can change the colors from the IDE, the fact that the theme (in its dark versions) doesn't allow to read the tooltip of the method summary is my mistake. Therefore I reopen the ticket to fix it.

**Comment by Lowfeye** [comment]
> @JobAbout thanks for your report: even if a user can change the colors from the IDE, the fact that the theme (in its dark versions) doesn't allow to read the tooltip of the method summary is my mistake. Therefore I reopen the ticket to fix it.

I really like this theme, thank you for porting the theme
