### ISSUE TITLE
Unreadable font colors for Lilac theme

### ISSUE THREAD

**Issue by GraceWXT** [pasqualedante/Noctis-visual-studio#2]
Hi,

The font color for Manage NuGet Packages window is white and is very low contrast with the lilac background. How can I change this to a higher contrast color?
![image](https://github.com/pasqualedante/Noctis-visual-studio/assets/98781479/375a6f9a-b6bc-4496-bfd2-9bbf9244e397)

**Comment by GraceWXT** [comment]
![image](https://github.com/pasqualedante/Noctis-visual-studio/assets/98781479/db2f037d-c83c-44b4-95ea-6981d75cced7)
This is another place where the font color contrast is not very user-friendly - when I select var `invoice` the highlight of the other references are too dark to read

**Comment by GraceWXT** [comment]
![image](https://github.com/pasqualedante/Noctis-visual-studio/assets/98781479/eab83ba7-9081-43b0-8e08-7203c94bd81d)
The find result highlight is also not readable

**Comment by pasqualedante** [comment]
Hi @GraceWXT , thanks for reporting this problem to me: there were several wrong colors set in 'dark' mode and not 'light' as it should have been.
